config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get '/about' => 'pages#about'
  get '/signups/new' => 'signups#new'
  post '/signups' => 'signups#create'
  get '/thanks' => 'signups#thanks'
  
  resources :signups
  

end

app/models/signup.rb
class Signup < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def about
    end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
    def new
        @signup = Signup.new
    end
    def create
        @signup = Signup.new(signup_params)
        if @signup.save
            redirect_to "/thanks"
        else
            render "/new"
        end
    end
    def thanks
    end
    private
    def signup_params
        params.require(:signup).permit(:firstname).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
	<html>
	<head>
	  <title>Stories</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	  <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,400,500' rel='stylesheet' type='text/css'>
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

<div class="menu">
	<h3>Menu <a href="#" class="menu-toggle">&times;</a></h3>
	<ul>
		<li><a href="/">Home<i class="fa fa-angle-right"></i></a></li>
		<li><a href="/about">About<i class="fa fa-angle-right"></i></a></li>
		<li><a href="/signups/new">Contact<i class="fa fa-angle-right"></i></a></li>
	</ul>
</div>

<div class="header">
	<a href="#" class="menu-toggle"><i class="fa fa-bars"></i> Menu</a>
</div>

	<%= yield %>

<div class="footer">
    <div class="container">
        <p>A Shutterbugg project</p>
    </div>    
</div>

	</body>
	</html>

app/views/pages/about.html.erb
<div class="about-main">
    <div class="content container">
        <h1>Relive great experiences</h1>
    </div>
</div>
<div class="about-supporting">
    <div class="container">
        <h2>No more storing and sorting photos</h2>
        <p>Stories automatically finds your photos and creates a travelogue for you. Capture and share experiences like never before.</p>
        <p>
            <%= link_to "Sign up", new_signup_path, :class => "btn btn-primary" %>
        </p>
    </div>
</div>

app/views/pages/home.html.erb
<div class="main">
    <div class="row">
        <div class="container">
            <div class="content col-md-6 pull-right">
              <h1>Create and share stories</h1>
              <p>
                <%= link_to "Learn more", about_path, :class => "btn btn-primary" %>
              </p>
            </div>
        </div>
    </div>  
</div>

<div class="supporting">
    <div class="container">
        <h2>Relive your adventures</h2>
        <p>Stories automatically creates a digital journal filled with your best photos and notes</p>
    </div>
</div>
<div class="secondary">
    <div class="container">
        
    </div>    
</div>
<div class="about">
    <div class="container">
        <h2>Find friends and share experiences</h2>
        <p>
            <%= link_to "Learn more", about_path, :class => "btn btn-primary" %>
        </p>
    </div>    
</div>

app/views/signups/new.html.erb
<div class="contact-main">
    <div class="content container">
        <h1>Get the latest updates from Stories</h1>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <%= form_for @signup, :html => {:class => "form"} do |f| %>

                    <%= f.label :first_name %>
                    <%= f.text_field :firstname %>
                    <%= f.label :email %>
                    <%= f.text_field :email %>
                    <%= f.submit "Join", :class => "btn btn-default" %>
                    
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/signups/thanks.html.erb
<div class="contact-main">
    <div class="content container">
        <h1>Thanks, we'll been in touch soon</h1>
    </div>
</div>